#!/bin/bash
branch="master"
initGit=true

while getopts "b:n" opt
do
    case "$opt" in
        "b") branch="$OPTARG" ;;
        "n") initGit=false ;;
    esac
done
shift $(($OPTIND - 1))

create=$1

#create a project directory if create parameter has been set
if [ ! -z "$create" ]
    then
        mkdir "$create"
        cd "$create"
fi

#clone the git project
git clone -b "$branch" --depth=1 git@github.com:Prophets/moeulleux.git .
#remove .git
rm -rf .git

if $initGit
    then
        #initialize new .git
        git init
        #add commit message hook
        cp git/hooks/prepare-commit-msg .git/hooks/prepare-commit-msg
fi

#remove git (template hooks) and bash folder
rm -rf git
rm -rf bash

if $initGit
    then
        #create inital commit
        git add -A
        git commit -m 'inital commit'
fi
